-- MySQL Script generated by MySQL Workbench
-- Mon Dec  4 20:53:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 77Transportes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 77Transportes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `77Transportes` DEFAULT CHARACTER SET utf8 ;
USE `77Transportes` ;

-- -----------------------------------------------------
-- Table `77Transportes`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `77Transportes`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `77Transportes`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `77Transportes`.`funcionarios` (
  `idfuncionarios` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`idfuncionarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `77Transportes`.`transporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `77Transportes`.`transporte` (
  `idtransportes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `preco` FLOAT NULL,
  `descricaotransporte` VARCHAR(100) NULL,
  `funcionarios_idfuncionarios` INT NOT NULL,
  PRIMARY KEY (`idtransportes`, `funcionarios_idfuncionarios`),
  INDEX `fk_transporte_funcionarios1_idx` (`funcionarios_idfuncionarios` ASC),
  CONSTRAINT `fk_transporte_funcionarios1`
    FOREIGN KEY (`funcionarios_idfuncionarios`)
    REFERENCES `77Transportes`.`funcionarios` (`idfuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `77Transportes`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `77Transportes`.`pagamento` (
  `idtipopagemento` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NULL,
  `titular` VARCHAR(45) NULL,
  `validade` VARCHAR(45) NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`idtipopagemento`, `usuarios_id`),
  INDEX `fk_pagamento_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_pagamento_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `77Transportes`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `77Transportes`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `77Transportes`.`endereco` (
  `idend` INT NOT NULL,
  `rua` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `numerocasa` INT NULL,
  `bairro` VARCHAR(100) NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`idend`, `usuarios_id`),
  INDEX `fk_endereco_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_endereco_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `77Transportes`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `77Transportes`.`aluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `77Transportes`.`aluguel` (
  `usuarios_id` INT NOT NULL,
  `transporte_id` INT NOT NULL,
  `datadoaluguel` DATETIME NULL,
  PRIMARY KEY (`usuarios_id`, `transporte_id`),
  INDEX `fk_usuarios_has_transporte_transporte1_idx` (`transporte_id` ASC),
  INDEX `fk_usuarios_has_transporte_usuarios_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_usuarios_has_transporte_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `77Transportes`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_transporte_transporte1`
    FOREIGN KEY (`transporte_id`)
    REFERENCES `77Transportes`.`transporte` (`idtransportes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
